#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/fusionwave/Documents/src/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/fusionwave/Documents/GitHub/GetIn-ScannerApp"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/fusionwave/Documents/GitHub/GetIn-ScannerApp/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=2.3.3"
export "FLUTTER_BUILD_NUMBER=80"
export "CONFIGURATION_BUILD_DIR=/Users/fusionwave/Documents/GitHub/GetIn-ScannerApp/build/ios/iphoneos"
export "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9BUFBfRkxBVk9SPXByb2Q=,RkxVVFRFUl9WRVJTSU9OPTMuMzguNg==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049OGI4NzI4Njg0OQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NzhmYzMwMTJlNA==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMC43"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/fusionwave/Documents/GitHub/GetIn-ScannerApp/.dart_tool/package_config.json"
export "FLAVOR=prod"
